name: flutter_technical_assessment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.10.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # --- State Management & Dependency Injection ---
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  dartz: ^0.10.1
  # --- Model Utilities ---
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  # --- Networking & API ---
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  internet_connection_checker: ^1.0.0+1
  # --- Firebase Services ---
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.4.9
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  # --- Local Storage & Device Info ---
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.1
  # --- Security & Database ---
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  local_auth: ^2.1.7
  local_auth_ios: ^1.1.7
  # --- Maps & Location ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  url_launcher: ^6.2.2
  # --- UI & Localization & Responsiveness ---
  advanced_responsive: ^1.0.3
  # --- Utils & Tools ---
  permission_handler: ^12.0.1
  performance_monitor: ^1.1.2
  mocktail: ^1.0.4
  shimmer: ^3.0.0
  cached_network_image: ^3.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # --- Generators ---
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
